collections:
  - name: community.general
    version: 8.6.11
  - name: prometheus.prometheus
    version: 0.27.4
  - name: ansible.posix
    version: 1.6.2
roles:
- name: geerlingguy.ansible
  src: geerlingguy.ansible
  version: 2.3.0
- name: geerlingguy.pip
  src: geerlingguy.pip
  version: 3.1.1
- name: geerlingguy.docker
  src: geerlingguy.docker
  version: 7.8.0
- name: artis3n.tailscale
  src: artis3n.tailscale
  version: v4.6.0
- name: patrickjahns.promtail
  src: patrickjahns.promtail
  version: 1.31.0
